// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package errcat

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func NewCatalog() catalog.Catalog {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"ru_RU": &dictionary{index: ru_RUIndex, data: ru_RUData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	return cat
}

var messageKeyToIndex = map[string]int{
	"2fa is disabled":                                                        72,
	"401. client is unauthorized":                                            4,
	"403. access forbidden":                                                  5,
	"404. resource not found":                                                7,
	"Validator_gte: %[1]s, %[2]s, %[3]s, %[4]s":                              87,
	"Validator_http_url: %[1]s, %[2]s, %[3]s":                                85,
	"Validator_lte: %[1]s, %[2]s, %[3]s, %[4]s":                              88,
	"Validator_max: %[1]s, %[2]s, %[3]s, %[4]s":                              89,
	"Validator_min: %[1]s, %[2]s, %[3]s, %[4]s":                              90,
	"Validator_required: %[1]s, %[2]s, %[3]s":                                86,
	"Validator_tag_2d_size: %[1]s, %[2]s, %[3]s":                             102,
	"Validator_tag_3d_size: %[1]s, %[2]s, %[3]s":                             103,
	"Validator_tag_article: %[1]s, %[2]s, %[3]s":                             91,
	"Validator_tag_email: %[1]s, %[2]s, %[3]s":                               92,
	"Validator_tag_email_phone: %[1]s, %[2]s, %[3]s":                         93,
	"Validator_tag_lang: %[1]s, %[2]s, %[3]s":                                94,
	"Validator_tag_name: %[1]s, %[2]s, %[3]s":                                95,
	"Validator_tag_password: %[1]s, %[2]s, %[3]s":                            96,
	"Validator_tag_phone: %[1]s, %[2]s, %[3]s":                               97,
	"Validator_tag_realm: %[1]s, %[2]s, %[3]s":                               98,
	"Validator_tag_rewrite_name: %[1]s, %[2]s, %[3]s":                        99,
	"Validator_tag_tz: %[1]s, %[2]s, %[3]s":                                  100,
	"Validator_tag_variable: %[1]s, %[2]s, %[3]s":                            101,
	"access forbidden":                                                       6,
	"after node with ID=%[1]s not found":                                     76,
	"all attempts to confirm the operation have been spent":                  57,
	"auth token is empty or invalid":                                         68,
	"auth token not found or expired":                                        69,
	"box article '%[1]s' already exists":                                     26,
	"box with ID=%[1]s not found":                                            25,
	"confirm code is incorrect":                                              55,
	"confirm code is required":                                               56,
	"disable current 2fa before setting a new one":                           73,
	"element template ID is required":                                        38,
	"element template with ID=%[1]s is disabled":                             40,
	"element template with ID=%[1]s not found":                               39,
	"email already exists":                                                   22,
	"email is invalid":                                                       20,
	"file is invalid":                                                        19,
	"form ID is required":                                                    31,
	"form element with ID=%[1]s not found":                                   36,
	"form with ID=%[1]s is disabled":                                         35,
	"form with ID=%[1]s not found":                                           32,
	"input data is incorrect: '%[1]s'":                                       17,
	"internal error":                                                         0,
	"invalid file extension: %[1]s":                                          79,
	"invalid file size, max size = %[1]sb":                                   78,
	"invalid file size, min size = %[1]sb":                                   77,
	"invalid file total size, max total size = %[1]sb":                       80,
	"invalid image height, max size = %[1]spx":                               84,
	"invalid image width, max size = %[1]spx":                                83,
	"item detailing '%[1]s' not allowed for form detailing '%[2]s'":          37,
	"laminate article '%[1]s' already exists":                                28,
	"laminate type ID is required":                                           41,
	"laminate type with ID=%[1]s is not available":                           42,
	"laminate type with ID=%[1]s not found":                                  43,
	"laminate with ID=%[1]s not found":                                       27,
	"login not exists":                                                       65,
	"no attempts to resend confirm code":                                     58,
	"not implemented":                                                        3,
	"operation already confirmed":                                            62,
	"operation already expired":                                              63,
	"operation is empty or invalid":                                          61,
	"operation is not confirmed":                                             64,
	"paper article '%[1]s' already exists":                                   30,
	"paper color ID is required":                                             44,
	"paper color with ID=%[1]s is not available":                             45,
	"paper color with ID=%[1]s not found":                                    46,
	"paper facture ID is required":                                           47,
	"paper facture with ID=%[1]s is not available":                           48,
	"paper facture with ID=%[1]s not found":                                  49,
	"paper with ID=%[1]s not found":                                          29,
	"param name '%[1]s' already exists":                                      34,
	"password has recovery code format":                                      67,
	"password is too weak":                                                   66,
	"phone already exists":                                                   23,
	"phone is invalid":                                                       21,
	"print format ID is required":                                            50,
	"print format with ID=%[1]s is not available":                            51,
	"print format with ID=%[1]s not found":                                   52,
	"query %[1]s not found":                                                  24,
	"record not found":                                                       8,
	"record version conflict":                                                9,
	"recovery code is not accepted at this step":                             74,
	"request body is not valid: '%[1]s'":                                     10,
	"request param with key '%[1]s' contains value greater then max '%[2]s'": 15,
	"request param with key '%[1]s' has value length greater then max '%[2]s' characters": 16,
	"request param with key '%[1]s' is empty":                                             14,
	"request param with key '%[1]s' of type '%[2]s' contains incorrect value '%[3]s'":     13,
	"resend confirm code is not supported for the current action":                         59,
	"rewrite name '%[1]s' already exists":                                                 33,
	"sending new messages is temporarily restricted":                                      60,
	"session limit exceeded, try again later":                                             70,
	"signup already in progress, try again later":                                         71,
	"switching from '%[1]s' to '%[2]s' is rejected":                                       18,
	"system error": 1,
	"the content type '%[1]s' does not match the detected type": 81,
	"the file with the specified key '%[1]s' was not uploaded":  12,
	"token not found or expired : %[1]s, %[2]s, %[1]s":          53,
	"token section %[1]s is invalid":                            54,
	"too many requests":                                         11,
	"totp code is incorrect":                                    75,
	"unexpected internal error":                                 2,
	"unsupported file type '%[1]s'":                             82,
}

var en_USIndex = []uint32{ // 105 elements
	// Entry 0 - 1F
	0x00000000, 0x00000016, 0x00000068, 0x0000009f,
	0x000000af, 0x000000cb, 0x000000fb, 0x0000012b,
	0x0000013e, 0x0000014f, 0x00000193, 0x00000201,
	0x0000022b, 0x00000264, 0x000002b2, 0x000002d5,
	0x00000321, 0x00000373, 0x00000394, 0x000003c2,
	0x000003d2, 0x000003eb, 0x00000403, 0x0000042c,
	0x00000454, 0x0000046a, 0x00000486, 0x000004ae,
	0x000004cf, 0x000004fc, 0x0000051a, 0x00000544,
	// Entry 20 - 3F
	0x00000558, 0x00000575, 0x00000599, 0x000005bf,
	0x000005de, 0x00000603, 0x00000644, 0x00000664,
	0x0000068d, 0x000006b8, 0x000006d5, 0x00000702,
	0x00000728, 0x00000743, 0x0000076e, 0x00000792,
	0x000007af, 0x000007dc, 0x00000802, 0x0000081e,
	0x0000084a, 0x0000086f, 0x0000089f, 0x000008be,
	0x000008dd, 0x000008fb, 0x00000930, 0x00000961,
	0x000009a9, 0x000009d8, 0x000009fe, 0x00000a1d,
	// Entry 40 - 5F
	0x00000a3b, 0x00000a56, 0x00000a7e, 0x00000a93,
	0x00000ac3, 0x00000af3, 0x00000b1c, 0x00000b4b,
	0x00000b81, 0x00000ba7, 0x00000bee, 0x00000c19,
	0x00000c30, 0x00000c76, 0x00000ca0, 0x00000cca,
	0x00000ce8, 0x00000d1e, 0x00000d62, 0x00000d80,
	0x00000dad, 0x00000ddc, 0x00000e19, 0x00000e2f,
	0x00000e7f, 0x00000ecc, 0x00000f02, 0x00000f4d,
	0x00000fa8, 0x00000fe7, 0x00001036, 0x0000108b,
	// Entry 60 - 7F
	0x0000110f, 0x00001188, 0x000011c8, 0x00001215,
	0x000012a4, 0x000012fa, 0x0000136c, 0x000013d6,
	0x0000144b,
} // Size: 444 bytes

const en_USData string = "" + // Size: 5195 bytes
	"\x02Internal server error\x02The service is temporarily unable to proces" +
	"s your request. Please try again later\x02Internal server error [problem" +
	"]\x0a\x0a599. unexpected error\x02Not implemented\x02User authorization " +
	"required\x02Forbidden - You don't have permission to access\x02Forbidden" +
	" - You don't have permission to access\x02Resource not found\x02Record n" +
	"ot found\x02Record version conflict, the record was modified by another " +
	"process\x02Request body is not valid: '%[1]s'\x0a\x0acheck the request p" +
	"arameters, the json format and the corresponding types\x02Too many reque" +
	"sts, please try again later\x02The file with the specified key '%[1]s' w" +
	"as not uploaded\x02Request parameter '%[1]s' of type '%[2]s' contains an" +
	" incorrect value '%[3]s'\x02Request parameter '%[1]s' is empty\x02Reques" +
	"t parameter '%[1]s' contains a value greater than the maximum '%[2]s'" +
	"\x02Request parameter '%[1]s' has a value longer than the maximum of %[2" +
	"]s characters\x02Input data is incorrect: '%[1]s'\x02Switching from '%[1" +
	"]s' to '%[2]s' is rejected\x02File is invalid\x02Email address is invali" +
	"d\x02Phone number is invalid\x02This email address is already registered" +
	"\x02This phone number is already registered\x02Query %[1]s not found\x02" +
	"Box with ID=%[1]s not found\x02Box with article '%[1]s' already exists" +
	"\x02Laminate with ID=%[1]s not found\x02Laminate with article '%[1]s' al" +
	"ready exists\x02Paper with ID=%[1]s not found\x02Paper with article '%[1" +
	"]s' already exists\x02Form ID is required\x02Form with ID=%[1]s not foun" +
	"d\x02Rewrite name '%[1]s' already exists\x02Parameter name '%[1]s' alrea" +
	"dy exists\x02Form with ID=%[1]s is disabled\x02Form element with ID=%[1]" +
	"s not found\x02Item detailing '%[1]s' is not allowed for form detailing " +
	"'%[2]s'\x02Element template ID is required\x02Element template with ID=%" +
	"[1]s not found\x02Element template with ID=%[1]s is disabled\x02Laminate" +
	" type ID is required\x02Laminate type with ID=%[1]s is not available\x02" +
	"Laminate type with ID=%[1]s not found\x02Paper color ID is required\x02P" +
	"aper color with ID=%[1]s is not available\x02Paper color with ID=%[1]s n" +
	"ot found\x02Paper facture ID is required\x02Paper facture with ID=%[1]s " +
	"is not available\x02Paper facture with ID=%[1]s not found\x02Print forma" +
	"t ID is required\x02Print format with ID=%[1]s is not available\x02Print" +
	" format with ID=%[1]s not found\x02Token not found or expired: %[1]s, %[" +
	"2]s, %[1]s\x02Token section %[1]s is invalid\x02Confirmation code is inc" +
	"orrect\x02Confirmation code is required\x02All attempts to confirm the o" +
	"peration have been used\x02No attempts left to resend the confirmation c" +
	"ode\x02Resending the confirmation code is not supported for the current " +
	"action\x02Sending new messages is temporarily restricted\x02Operation is" +
	" not specified or invalid\x02Operation is already confirmed\x02Operation" +
	" has already expired\x02Operation is not confirmed\x02User with the spec" +
	"ified login not found\x02Password is too weak\x02Password must not have " +
	"the recovery code format\x02Authorization token is not specified or inva" +
	"lid\x02Authorization token not found or expired\x02Session limit exceede" +
	"d, please try again later\x02Signup is already in progress, please try a" +
	"gain later\x02Two-factor authentication is disabled\x02Disable the curre" +
	"nt two-factor authentication before setting a new one\x02Recovery code i" +
	"s not accepted at this step\x02TOTP code is incorrect\x02Node with ID=%[" +
	"1]s, after which the insertion is performed, not found\x02Invalid file s" +
	"ize, minimum size = %[1]s b\x02Invalid file size, maximum size = %[1]s b" +
	"\x02Invalid file extension: %[1]s\x02Invalid total file size, maximum to" +
	"tal size = %[1]s b\x02The specified content type '%[1]s' does not match " +
	"the detected type\x02Unsupported file type '%[1]s'\x02Invalid image widt" +
	"h, maximum width = %[1]spx\x02Invalid image height, maximum height = %[1" +
	"]spx\x02The field value must be URL address (current value: '%[3]s')\x02" +
	"The field is required\x02The field value must be greater than or equal t" +
	"o %[4]s (current value: '%[3]s')\x02The field value must be less than or" +
	" equal to %[4]s (current value: '%[3]s')\x02The field value must be no m" +
	"ore than %[4]s characters\x02The field value must be at least %[4]s char" +
	"acters (current value: '%[3]s')\x02The field value must not be empty and" +
	" must not contain whitespace (current value: '%[3]s')\x02The field value" +
	" must be email address (current value: '%[3]s')\x02The field value must " +
	"be email address or phone number (current value: '%[3]s')\x02The field v" +
	"alue must be one of the supported language codes (current value: '%[3]s'" +
	")\x02The field value must start and end with a latin letter or a digit a" +
	"nd may contain the characters / _ . + - (current value: '%[3]s')\x02The " +
	"field value must contain only latin letters, numbers, and special charac" +
	"ters without spaces (current value: '%[3]s')\x02The field value must be " +
	"a phone number (current value: '%[3]s')\x02The field value must be one o" +
	"f the supported realms (current value: '%[3]s')\x02The field value must " +
	"start with a lowercase latin letter and contain only lowercase latin let" +
	"ters, digits and hyphens (current value: '%[3]s')\x02The field value mus" +
	"t be one of the supported time zone names (current value: '%[3]s')\x02Th" +
	"e field value must start with a latin letter and contain only latin lett" +
	"ers and digits (current value: '%[3]s')\x02The field value must be a siz" +
	"e in the 'lengthxwidth' format, for example 100x200 (current value: '%[3" +
	"]s')\x02The field value must be a size in the 'lengthxwidthxheight' form" +
	"at, for example 100x200x300 (current value: '%[3]s')"

var ru_RUIndex = []uint32{ // 105 elements
	// Entry 0 - 1F
	0x00000000, 0x00000031, 0x000000ca, 0x00000105,
	0x0000012a, 0x0000016d, 0x0000019d, 0x000001cd,
	0x0000020e, 0x0000022f, 0x000002a2, 0x00000370,
	0x000003c9, 0x0000041a, 0x00000496, 0x000004d4,
	0x0000054e, 0x000005ed, 0x00000629, 0x0000067d,
	0x0000069f, 0x000006c9, 0x000006fe, 0x00000748,
	0x0000079d, 0x000007c2, 0x000007f1, 0x0000083a,
	0x00000867, 0x000008b0, 0x000008dd, 0x00000924,
	// Entry 20 - 3F
	0x00000944, 0x0000096f, 0x000009af, 0x000009ed,
	0x00000a17, 0x00000a4f, 0x00000ac7, 0x00000afc,
	0x00000b38, 0x00000b73, 0x00000ba2, 0x00000bdb,
	0x00000c11, 0x00000c3e, 0x00000c75, 0x00000ca9,
	0x00000cda, 0x00000d17, 0x00000d53, 0x00000d84,
	0x00000dbf, 0x00000df7, 0x00000e5c, 0x00000e95,
	0x00000ec8, 0x00000efd, 0x00000f52, 0x00000fc3,
	0x00001056, 0x000010ab, 0x000010ee, 0x0000111f,
	// Entry 40 - 5F
	0x00001155, 0x00001184, 0x000011d4, 0x000011fd,
	0x00001264, 0x000012b6, 0x0000131d, 0x00001374,
	0x000013d7, 0x00001422, 0x000014a7, 0x000014f4,
	0x00001511, 0x0000157c, 0x000015dd, 0x00001640,
	0x00001680, 0x0000170b, 0x0000177d, 0x000017b8,
	0x00001826, 0x00001894, 0x00001908, 0x00001944,
	0x000019c2, 0x00001a40, 0x00001a97, 0x00001b17,
	0x00001bbe, 0x00001c36, 0x00001cd5, 0x00001d7f,
	// Entry 60 - 7F
	0x00001e72, 0x00001f51, 0x00001fd4, 0x00002084,
	0x0000218b, 0x00002246, 0x0000231d, 0x000023d7,
	0x000024a2,
} // Size: 444 bytes

const ru_RUData string = "" + // Size: 9378 bytes
	"\x02Внутренняя ошибка сервера\x02Сервис временно не может обработать ваш" +
	" запрос. Пожалуйста, повторите запрос позже\x02Внутренняя ошибка сервера" +
	" [problem]\x02Метод не реализован\x02Требуется авторизация пользователя" +
	"\x02Доступ к ресурсу отклонён\x02Доступ к ресурсу отклонён\x02Запрашивае" +
	"мый ресурс не был найден\x02Запись не найдена\x02Конфликт версий записи" +
	", запись была изменена другим процессом\x02Тело запроса невалидное: '%[1" +
	"]s'\x0a\x0aпроверьте параметры запроса, правильность формата json и соот" +
	"ветствующих ему типов\x02Слишком много запросов, повторите попытку позж" +
	"е\x02Файл с указанным ключом '%[1]s' не был загружен\x02Параметр запрос" +
	"а '%[1]s' типа '%[2]s' содержит некорректное значение '%[3]s'\x02Параме" +
	"тр запроса '%[1]s' не заполнен\x02Параметр запроса '%[1]s' содержит зна" +
	"чение больше максимального '%[2]s'\x02Длина значения параметра запроса " +
	"'%[1]s' превышает максимально допустимую в %[2]s символов\x02Входные дан" +
	"ные некорректны: '%[1]s'\x02Переход из статуса '%[1]s' в статус '%[2]s'" +
	" запрещён\x02Некорректный файл\x02Некорректный email адрес\x02Некорректн" +
	"ый номер телефона\x02Указанный email адрес уже зарегистрирован\x02Указа" +
	"нный номер телефона уже зарегистрирован\x02Запрос %[1]s не найден\x02Ко" +
	"робка с ID=%[1]s не найдена\x02Коробка с артикулом '%[1]s' уже существу" +
	"ет\x02Ламинат с ID=%[1]s не найден\x02Ламинат с артикулом '%[1]s' уже с" +
	"уществует\x02Бумага с ID=%[1]s не найдена\x02Бумага с артикулом '%[1]s'" +
	" уже существует\x02Не указан ID формы\x02Форма с ID=%[1]s не найдена\x02" +
	"Символьное имя '%[1]s' уже существует\x02Имя параметра '%[1]s' уже суще" +
	"ствует\x02Форма с ID=%[1]s отключена\x02Элемент формы с ID=%[1]s не най" +
	"ден\x02Детализация элемента '%[1]s' недопустима для детализации формы '" +
	"%[2]s'\x02Не указан ID шаблона элемента\x02Шаблон элемента с ID=%[1]s не" +
	" найден\x02Шаблон элемента с ID=%[1]s отключён\x02Не указан ID типа лами" +
	"ната\x02Тип ламината с ID=%[1]s недоступен\x02Тип ламината с ID=%[1]s н" +
	"е найден\x02Не указан ID цвета бумаги\x02Цвет бумаги с ID=%[1]s недосту" +
	"пен\x02Цвет бумаги с ID=%[1]s не найден\x02Не указан ID фактуры бумаги" +
	"\x02Фактура бумаги с ID=%[1]s недоступна\x02Фактура бумаги с ID=%[1]s не" +
	" найдена\x02Не указан ID формата печати\x02Формат печати с ID=%[1]s недо" +
	"ступен\x02Формат печати с ID=%[1]s не найден\x02Токен не найден или сро" +
	"к его действия истёк: %[1]s, %[2]s, %[1]s\x02Некорректная секция токена" +
	" %[1]s\x02Неверный код подтверждения\x02Требуется код подтверждения\x02И" +
	"счерпаны все попытки подтверждения операции\x02Исчерпаны все попытки по" +
	"вторной отправки кода подтверждения\x02Повторная отправка кода подтверж" +
	"дения не поддерживается для текущего действия\x02Отправка новых сообщен" +
	"ий временно ограничена\x02Операция не указана или некорректна\x02Операц" +
	"ия уже подтверждена\x02Срок действия операции истёк\x02Операция не подт" +
	"верждена\x02Пользователь с указанным логином не найден\x02Пароль слишко" +
	"м слабый\x02Пароль не должен совпадать по формату с аварийным кодом\x02" +
	"Токен авторизации не указан или некорректен\x02Токен авторизации не най" +
	"ден или срок его действия истёк\x02Превышен лимит сессий, повторите поп" +
	"ытку позже\x02Регистрация уже выполняется, повторите попытку позже\x02Д" +
	"вухфакторная аутентификация отключена\x02Отключите текущую двухфакторну" +
	"ю аутентификацию перед настройкой новой\x02Аварийный код на этом шаге н" +
	"е принимается\x02Неверный TOTP код\x02Узел с ID=%[1]s, после которого в" +
	"ыполняется вставка, не найден\x02Недопустимый размер файла, минимальный" +
	" размер = %[1]s б\x02Недопустимый размер файла, максимальный размер = %[" +
	"1]s б\x02Недопустимое расширение файла: %[1]s\x02Недопустимый суммарный " +
	"размер файлов, максимальный суммарный размер = %[1]s б\x02Указанный тип" +
	" содержимого '%[1]s' не соответствует фактическому\x02Неподдерживаемый т" +
	"ип файла '%[1]s'\x02Недопустимая ширина изображения, максимальная ширин" +
	"а = %[1]spx\x02Недопустимая высота изображения, максимальная высота = %" +
	"[1]spx\x02Значение поля должно являться URL адресом (текущее значение: %" +
	"[3]s)\x02Поле обязательно для заполнения\x02Значение поля должно быть бо" +
	"льше или равно %[4]s (текущее значение: %[3]s)\x02Значение поля должно " +
	"быть меньше или равно %[4]s (текущее значение: %[3]s)\x02Значение поля " +
	"должно быть не более %[4]s символов\x02Значение поля должно быть не мен" +
	"ее %[4]s символов (текущее значение: %[3]s)\x02Значение поля не должно " +
	"быть пустым и содержать пробельные символы (текущее значение: '%[3]s')" +
	"\x02Значение поля должно являться email адресом (текущее значение: '%[3]" +
	"s')\x02Значение поля должно являться email адресом или номером телефона " +
	"(текущее значение: '%[3]s')\x02Значение поля должно являться кодом одног" +
	"о из поддерживаемых языков (текущее значение: '%[3]s')\x02Значение поля" +
	" должно начинаться и заканчиваться латинской буквой или цифрой и может с" +
	"одержать символы / _ . + - (текущее значение: '%[3]s')\x02Значение поля" +
	" должно содержать только латинские буквы, цифры и специальные символы кр" +
	"оме пробела (текущее значение: '%[3]s')\x02Значение поля должно являтьс" +
	"я номером телефона (текущее значение: '%[3]s')\x02Значение поля должно " +
	"являться одной из поддерживаемых областей доступа (текущее значение: '%" +
	"[3]s')\x02Значение поля должно начинаться со строчной латинской буквы и " +
	"содержать только строчные латинские буквы, цифры и дефис (текущее значе" +
	"ние: '%[3]s')\x02Значение поля должно являться именем одного из поддерж" +
	"иваемых часовых поясов (текущее значение: '%[3]s')\x02Значение поля дол" +
	"жно начинаться с латинской буквы и содержать только латинские буквы и ц" +
	"ифры (текущее значение: '%[3]s')\x02Значение поля должно являться разме" +
	"ром в формате 'длинаxширина', например 100x200 (текущее значение: '%[3]" +
	"s')\x02Значение поля должно являться размером в формате 'длинаxширинаxвы" +
	"сота', например 100x200x300 (текущее значение: '%[3]s')"

	// Total table size 15461 bytes (15KiB); checksum: 8F509871
